### ISSUE TITLE
How to install it and compile on my local computer?

### ISSUE THREAD

**Issue by Deutsch4534** [blackholeorganization/BlackHoleProtocol#1]
Do you have tutorials? I didn’t find any guides about it.

**Comment by Walterion01** [comment]
The code is ready for preview and test for everybody. You are welcome to test it, and for that, you need to get the Truck version of Lazarus and needed packages as stated in the readme. No other dependency is required.
As for tutorials, there is not any for now.

**Comment by Deutsch4534** [comment]
Do I need to install all the packages?

Synopse mORMot framework
CryptoLib4Pascal
Synapse
BlockStack
BGRABitmap
BGRA Controls

**Comment by Walterion01** [comment]
All stated packages in the readme should be added. Lazarus will warn you if any package is missing and help you to find it.

**Comment by Deutsch4534** [comment]
Do my files stored in Gaiahub or your server? If your site(blackhole.run) goes down and not run more, how can I find all my files back? Do you have any ways to check and find all the download links of uploaded files?

Do you have answers for these questions?   @Walterion1

**Comment by Walterion01** [comment]
Gaia. You can use the provided free hub or use another one. In the current plan, you can see only the last file. No matter what provider you are using, all data will be encrypted so that data will always be safe.

**Comment by Deutsch4534** [comment]
I tried to retrieve files via https://michaelfedora.github.io/mercurius/ 
and got some files, but those totally messy codes:


![屏幕快照 2019-06-13 下午1 05 13](https://user-images.githubusercontent.com/12605959/59405677-e6253e00-8ddd-11e9-9e71-7136e356fd51.png)
![屏幕快照 2019-06-13 下午1 05 26](https://user-images.githubusercontent.com/12605959/59405678-e6253e00-8ddd-11e9-9477-a6bb643851a8.png)
![屏幕快照 2019-06-13 下午1 19 05](https://user-images.githubusercontent.com/12605959/59405679-e6bdd480-8ddd-11e9-8718-ea043f0d88f6.png)


So , How to retrieve files from blackhole.run , and download those files via GaiaHub? Do you have easy ways?

@Walterion1

**Comment by Walterion01** [comment]
Because of high security level, all of the files will be encrypted heavily so they should be like messy codes. But you can get them easily with the private link/key.
There is no interface available right now, but you can do it with the available API.

**Comment by Deutsch4534** [comment]
@Walterion1  How to get them with my private key? And how to do it with the available API?
