### ISSUE TITLE
Error when running the installer

### ISSUE THREAD

**Issue by nordflow** [blackholeorganization/BlackHoleProtocol#2]
When running the installer.
> ShellExecuteEx failed; 299
> Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

**Comment by rss-dev** [comment]
ShellExecuteEx failed; 299 when running the installer.

**Comment by nordflow** [comment]
AVAST AntiVirus was the problem. It throws error messages when launching Inno Setups.
