### ISSUE TITLE
Linux desktop app?

### ISSUE THREAD

**Issue by Atrate** [blackholeorganization/BlackHoleProtocol#3]
It would be nice if there was a Linux desktop app or at least a CLI tool. BlackHole is amazing, but it would really help to have an app for Linux.

**Comment by Walterion01** [comment]
Hey,
We have a Terminal version under private tests. Hope we can release it soon.

**Comment by JayBrown** [comment]
fyi: a version of the CLI for macOS would be awesome, too!

**Comment by jakiisheep** [comment]
Any info about this?
