### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by xordiet** [blackholeorganization/BlackHoleProtocol#4]
In the windows version, I open the app, I go to the login button in bottom right,

![image](https://user-images.githubusercontent.com/23172437/68383257-9a40b000-0155-11ea-92dd-c7e863f697dc.png)

It opens blockstack web and ask me for authentication, I select my blockstack id, and accept, It ask me for open the app

![image](https://user-images.githubusercontent.com/23172437/68383561-2e127c00-0156-11ea-8e87-93072c6845d1.png)

I press to open app, and it opens a new window asking me for login. I have a secon one that seems loged, but I can't press "continue" or anythyng....

![image](https://user-images.githubusercontent.com/23172437/68383022-243c4900-0155-11ea-93bd-bf16570c44ec.png)

**Comment by xordiet** [comment]
> In the windows version, I open the app, I go to the login button in bottom right,
> 
> ![image](https://user-images.githubusercontent.com/23172437/68383257-9a40b000-0155-11ea-92dd-c7e863f697dc.png)
> 
> It opens blockstack web and ask me for authentication, I select my blockstack id, and accept, It ask me for open the app
> 
> ![image](https://user-images.githubusercontent.com/23172437/68382605-5d27ee00-0154-11ea-8c9b-a88f4746b425.png)
> 
> I press to open app, and it opens a new window asking me for login. I have a secon one that seems loged, but I can't press "continue" or anythyng....
> 
> ![image](https://user-images.githubusercontent.com/23172437/68383022-243c4900-0155-11ea-93bd-bf16570c44ec.png)

**Comment by Walterion01** [comment]
It seems you have two instances of the app.
Can you please uninstall the app completely? Make sure you delete all the files about the app, so you must not have these folders:
"C:\Program Files\BlackHole"
"C:\Users\{User}\AppData\Local\BlackHole"

After that, you can install it and try again.

**Comment by xordiet** [comment]
I've tryed several times, but allways same issue
![image](https://user-images.githubusercontent.com/23172437/71252322-f71eb100-2324-11ea-99d2-e3d0eb80f10d.png)

**Comment by konrei** [comment]
It's the same for me in Windows and macOS too. Looks like the development of the app has stopped.

**Comment by Walterion1** [comment]
Thanks for reporting this. It was a website issue, and it is now solved.
Please let me know if there was any problem.
